# Generated by Django 3.2.17 on 2023-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=250)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
